#!/usr/bin/env python3

lines = []
tomb = ''
def output():
    global lines
    global tomb
    if len(lines) == 0 or tomb == '':
        return
    fp1 = open("tomb/"+tomb+".ttl", "wt", encoding="utf-8")
    fp1.write(''.join(lines))
    fp1.close()
    lines = []
    tomb = ''

fp = open("tombs.ttl", "rt", encoding="utf-8")
lines = []
for line in fp:
    if line.startswith('###'):
        output()
        a = line.split()
        if len(a) == 2:
            tomb = a[1]
    else:
        lines.append(line)
output()
fp.close()
