#!/usr/bin/env python3

import sys

sys.stdout.write('''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
<name>begraafplaatsen</name>
''')

fp = open('sites.csv', 'rt')
for line in fp:
    lat, lon, name = line.strip().split(',', maxsplit=2)
    if lat == 'lat':
        continue
    lat1, lat2 = lat.split('/')
    lon1, lon2 = lon.split('/')
    lat = float(lat1) / float(lat2)
    lon = float(lon1) / float(lon2)
    name = name.strip('"')
    sys.stdout.write('''<Placemark>
  <name>{}</name>
  <Point>
    <coordinates>{:.4f},{:.4f},0</coordinates>
  </Point>
</Placemark>
'''.format(name, lon, lat))

fp.close()

sys.stdout.write('''</Document>
</kml>
''')
