#!/bin/bash

function NOP {
    echo "#$*"
}

ECHO=echo
if [ "$1" = "-n" ]
then
    ECHO=NOP
fi

unset CDPATH

cd `dirname $0`

cat prefix.ttl
echo

$ECHO '<ns> {'
cat ns.ttl
echo
$ECHO '}'

cd item
fgrep -h '@prefix' *.ttl
echo
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<item/$name> {"
    echo "item:$name :dcModified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    fgrep -h -v '@prefix' $i | ../../tools/name2soundex
    echo
    $ECHO "}"
done

cd ../bible
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<bible/$name> {"
    echo "bible:$name :dcModified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

cd ../site
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<site/$name> {"
    echo "site:$name :dcModified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

cd ../place
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<place/$name> {"
    echo "place:$name :dcModified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

cd ../symbol
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<symbol/$name> {"
    echo "symbol:$name :dcModified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

$ECHO "<meta> {"
echo "  <https://noordergraf.rug.nl/> :dcModified \"`date -u -Iseconds`\"^^xsd:dateTime ."
$ECHO "}"
echo
