#!/bin/bash

function NOP {
    echo "#$*"
}

ECHO=echo
if [ "$1" = "-n" ]
then
    ECHO=NOP
fi

unset CDPATH

cd `dirname $0`

cat prefix.ttl
echo

$ECHO '<ns> {'
cat ns.ttl
echo
$ECHO '}'

$ECHO '<bible> {'
cat bible.ttl
echo
$ECHO '}'

cd tomb
fgrep -h '@prefix' *.ttl
echo
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<tomb/$name> {"
    echo "tomb:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    fgrep -h -v '@prefix' $i | ../../tools/name2soundex
    echo
    $ECHO "}"
done

cd ../site
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<site/$name> {"
    echo "site:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

cd ../place
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<place/$name> {"
    echo "place:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

cd ../symbol
for i in *.ttl
do
    name="`basename $i .ttl`"
    $ECHO "<symbol/$name> {"
    echo "symbol:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo
    $ECHO "}"
done

$ECHO "<meta> {"
echo "  <https://noordergraf.rug.nl/> dc:modified \"`date -u -Iseconds`\"^^xsd:dateTime ."
$ECHO "}"
echo
