#!/bin/bash

unset CDPATH

cd `dirname $0`

cat prefix.ttl

echo '<ns> {'
cat ns.ttl
echo '}'

cd tomb
fgrep -h '@prefix' *.ttl
for i in *.ttl
do
    name="`basename $i .ttl`"
    echo "<tomb/$name> {"
    echo "tomb:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    fgrep -h -v '@prefix' $i
    echo "}"
done

cd ../site
for i in *.ttl
do
    name="`basename $i .ttl`"
    echo "<site/$name> {"
    echo "site:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo "}"
done

cd ../place
for i in *.ttl
do
    name="`basename $i .ttl`"
    echo "<place/$name> {"
    echo "place:$name dc:modified \"`date -u -Iseconds -r$i`\"^^xsd:dateTime ."
    cat $i
    echo "}"
done

echo "GRAPH <meta> {"
echo "  <> dc:modified \"`date -u -Iseconds`\"^^xsd:dateTime ."
echo "}"

