#!/bin/bash

set -e

. secret.sh

agtool load \
       --overwrite \
       --bulk \
       --duplicates delete \
       --automate-nd-datatype-mappings \
       --input trig \
       --optimize \
       --base-uri https://noordergraf.rug.nl/ \
       noordergraf \
       -

echo

python3 ../tools/mkfti.py
../tools/chkll
../tools/chklocation
../tools/chktags
../tools/mkprops > ns.json
../tools/mkbibidx > bible/index.body.eng
../tools/mkbibidx -n > bible/index.body.nld
../tools/mksymidx > ../www/picto/index.body.eng
../tools/mksymidx -n > ../www/picto/index.body.nld

../tools/prefix2allegro.py > /home/p209327/opt/agraph/data/settings/default-namespaces
mkdir -p /home/p209327/opt/agraph/data/rootcatalog/noordergraf/namespaces
../tools/prefix2allegro.py > /home/p209327/opt/agraph/data/rootcatalog/noordergraf/namespaces/anonymous
../tools/prefix2allegro.py > /home/p209327/opt/agraph/data/rootcatalog/noordergraf/namespaces/peter

echo OK
echo
