#!/bin/bash

. secret.sh

agtool load \
       --overwrite \
       --bulk \
       --duplicates delete \
       --automate-nd-datatype-mappings \
       --input trig \
       --optimize \
       --base-uri https://noordergraf.rug.nl/ \
       noordergraf \
       - \
  && python3 mkfti.py \
  && ../tools/chkll \
  && ../tools/mksymidx > ../www/sym/index.body.eng \
  && ../tools/mksymidx -n > ../www/sym/index.body.nld
