#!/usr/bin/env python3

def output():
    if len(lines) == 0:
        return
    fp1 = open("tomb/"+file+".ttl", "wt", encoding="utf-8")
    fp1.write(''.join(lines))
    fp1.close()
    lines = []
        

fp = open("tombs.txt", "rt", encoding="utf-8")
lines = []
for line in fp:
    if line.startswith('###'):
        output()
        a = line.split()
        if len(a) == 2:
            file = a[1]
    else:
        lines.append(line)
output()
fp.close()
